### PR TITLE
Add Roman Glushko to PHP mentor list

### PR DESCRIPTION
**Pull request by roma-glushko**

### CODE REVIEW

**Comment by roma-glushko** [comment]
Hi @rpottsoh,

Thank you for mentioning this. Can you please take a look again?
I have adjusted the json file.

- Roman

**Comment by roma-glushko** [comment]
@rpottsoh Wow Ryan, you are super attentive 😮 There were some additional spaces, sorry for that. Should be fixed now 🙏

**Comment by rpottsoh** [comment]
I am not sure how the emojis will appear on the site.  Look for your bio on the site after this gets merged.  If they don't appear as expected you will to open another PR to tweek your bio statement.

**Comment by roma-glushko** [comment]
@rpottsoh no problem, thank you!

**Pull request merged**
