### PR TITLE
rust/clock: struct literals vs new

### PR DESCRIPTION
**Pull request by bobahop**
The student may appreciate having explained how a struct literal can bypass the logic in a "new" function.

### CODE REVIEW

**Review by SleeplessByte — APPROVED** [review]
LGTM. Same as the other notes (feel free to merge using Squash merge, if the website-copy-rust team doesn't get to this in a timely manner).

**Review by SleeplessByte — APPROVED** [review]
Hehehehe self-approving.

**Comment by angelikatyborska** [comment]
@bobahop the PR has an approval, I think that means you can merge it?

**Comment by bobahop** [comment]
Thanks. Sorry, why wouldn't the approval merge it? What is left for me to do? I only see the option to close the PR. I don't have write access to this repo.

**Comment by angelikatyborska** [comment]
Oh, that means I still don't understand how GitHub permissions work 😅. I would assume the author of the PR can always merge when the required checks and approvals are in place, but apparently not. In that case, based on @SleeplessByte comments and approval, I'll allow myself to merge.

**Comment by bobahop** [comment]
Thank you!

**Pull request merged**
