### PR TITLE
[R] Add sum-of-multiples mentor notes

### PR DESCRIPTION
**Pull request by katrinleinweber**
Dear fellow @exercism/r maintainers & @exercism/r-contributors,

based on [`solutions/f34`](https://exercism.io/mentor/solutions/f3427a09bd114abdb76eeba72ae75a97) & [`solutions/e50`](https://exercism.io/mentor/solutions/e50a852f8b084e1a9c1e575ca959f798) I started compiling some notes. What do you think?

I think we should aggregate more of our advice into shared notes in order to give learners advice that we all stand behind and also to disseminate knowledge among us.

### CODE REVIEW

**Comment by jonmcalder** [comment]
Thanks for this @katrinleinweber! Looks pretty good to me - nice that you've referenced those resources too.

**Comment by rpottsoh** [comment]
Do any of the `R` maintainers/mentors have write access here?  Some should....

**Comment by SleeplessByte** [comment]
@exercism/r @exercism/r-contributors see comment ☝️

**Comment by katrinleinweber** [comment]
I don't have.

**Comment by jonmcalder** [comment]
Me neither.

**Comment by rpottsoh** [comment]
@iHiD or @kytrinyx R needs some people with write access I believe.

**Comment by kytrinyx** [comment]
(Not sure if this was mentioned anywhere, but write access has been given :))

**Pull request merged**
