### PR TITLE
javascript mentor biogram for pablo83

### PR DESCRIPTION
**Pull request by pablo83**

### CODE REVIEW

**Comment by kotp** [comment]
Edit from Polish to English.

**Comment by rpottsoh** [comment]
> Edit from Polish to English.

I have opened #765.

**Comment by kotp** [comment]
I only meant that the Polish "biogram" is changed to "biography" in the title.  The author knows how to represent their name, and so that should not.

**Comment by rpottsoh** [comment]
IC now.

**Comment by pablo83** [comment]
Hi, sorry for my mistake, I was sure word "biogram" exist in english too, my mistake.
The letter replaced in my name is ok, it could be `l` or` ł`. For better understanding we could keep `l`.

**Comment by kotp** [comment]
I like your name as it is... :)

**Pull request merged**
