### PR TITLE
Simplify ruby/scrabble-score

### PR DESCRIPTION
**Pull request by iHiD**
Add a simpler reasonable solution.

### CODE REVIEW

**Comment by pgaspar** [comment]
I like this exercise 🙂 I'm going through it [here](https://exercism.io/my/solutions/2eecc37d4c934cc3a2fec10c93dee4f8?iteration_idx=3) and I also struggle in the trade-offs between solutions like these and "score per letter" solutions like @F3PiX is suggesting.

This is probably one of those exercises where mentoring is more nuanced because, at least to me, both approaches have interesting advantages and it ends up depending on what you value most: performance or a clearer link between exercise instructions and the data representation on the solution.

Anyway, :+1: on these changes!

**Comment by F3PiX** [comment]
Thanks Jeremy!

**Comment by iHiD** [comment]
Thanks both. I really like this exercise too. It's my favourite on the track so far.

**Comment by iHiD** [comment]
(both to do and to mentor)

**Pull request merged**
