### PR TITLE
Create add mentor bio for ruby

### PR DESCRIPTION
**Pull request by AlekhyaR**

### CODE REVIEW

**Comment by rpottsoh** [comment]
@AlekhyaR do you need a hand with your bio?

**Comment by rpottsoh** [comment]
Pinging @AlekhyaR

**Comment by sshine** [comment]
@AlekhyaR: Would you like for your mentor bio to be committed, or have you decided against it?

We'll give it some weeks more and close or merge this PR depending on your response. :-)

**Comment by F3PiX** [comment]
I'm closing this. 
@AlekhyaR, In case you want to add yourself as a mentor, see [rpottsoh's comment above](https://github.com/exercism/website-copy/pull/896#pullrequestreview-217747005)

**Pull request closed without merging**
