### PR TITLE
Rust: Bob - give a reason for using constants

### PR DESCRIPTION
**Pull request by efx**
This relates to the slack [thread](https://exercism-team.slack.com/archives/CASLGD18D/p1567640988021800) where I asked about why we don't give *whys* for some recommendations to improving solution. As I mentor solutions I'll open these smaller PRs to fill out the notes.

### CODE REVIEW

**Comment by SleeplessByte** [comment]
cc @TheDarkula

**Comment by efx** [comment]
@TheDarkula any objections here?

**Comment by efx** [comment]
@Aloso and I actually had this conversation and, in this case, the compiler will optimize either way. So based on my limited understanding I don't think using a `const` is for performance here. I don't  agree then with giving performance as the primary justification.
Any thoughts Aloso? I can also pose a discussion on the rust users discourse.

**Comment by efx** [comment]
Given we have demoted Bob I will probably end up closing this PR too.

**Comment by efx** [comment]
Forgive my naivete here as well. I am striving to reconcile the conflict for personal sanity and to mentor better. I plugged in an example to [godbolt.org](https://godbolt.org/z/8WGqR-) and the machine code output does not look different when using a `const` or plain `i64`. Note this is based on the gigasecond example so may differ from strings.

**Pull request closed without merging**
