### PR TITLE
Ruby: Short note on DRY - High scores

### PR DESCRIPTION
**Pull request by programatologist**
DRY - Do not Repeat Yourself concept in Ruby.

### CODE REVIEW

**Comment by kotp** [comment]
Any reason this is closed @programatologist ?

**Comment by programatologist** [comment]
@kotp 
After while of creating this PR, I have got unsure that this is a right recommendation, thought recommend after a bit more check!

**Comment by kotp** [comment]
So perhaps unsure if DRY isn't a more general principle that probably gets mentioned, rather than something specific to this exercise?

**Comment by kotp** [comment]
I do mention that aspect when mentoring this exercise.  But not because of DRY, but because that set is smaller.

**Pull request closed without merging**
