### PR TITLE
add bio paulorosa

### PR DESCRIPTION
**Pull request by paulorosa**
add my bio

### CODE REVIEW

**Comment by paulorosa** [comment]
add bio paulorosa

**Comment by rpottsoh** [comment]
I have corrected the indentation issue.  Also, it appears as though you created the branch for this PR off of branch `r-mentor-notes` instead of `Master`.  This created a conflict which has been resolved.

I'll be merging your bio shortly.  Thanks for joining Java track team!

**Comment by rpottsoh** [comment]
Nah, it is still not right.  I only managed to merge into r-mentor-notes.

**Comment by rpottsoh** [comment]
@paulorosa you have had a little bit of a time of it I am afraid.  You have tried twice to open PRs for adding your bio information.  Both times you did that you were not checked into exercism/master branch but rather the r-mentor-notes branch, which I have since removed from exercism/master.  

Please try again.  I am not sure if you are working directly via the GitHub website or locally and using git.  I'll assume the website.  Make sure that exercism/master is the branch you are looking at before you open the json file to input your bio data.  When you finish making your changes GitHub will create a branch off of master in a fork that contain your changes to the file.  Since you already have a fork of this repo that is not current with (behind) exercism/website-copy, I recommend deleting your fork first.  Make sure you are connected to exercism/website-copy and not paulorosa/website-copy when you make your changes to the json file.

If you have any questions on how to proceed feel free to respond here or you can find me on Slack as well.

**Pull request merged**
