### PR TITLE
[Java Two-Fer] Identify code in the suggestions

### PR DESCRIPTION
**Pull request by PTrottier**
Write the code described in Java syntax to make it more approachable to Java mentors.

### CODE REVIEW

**Comment by SleeplessByte** [comment]
@PTrottier would you be so kind to rebase/resolve conflicts? The issue here is that the exercise is called `two-fer`. #741 fixed this, but that means that the file you made the change on has been deleted. Can you apply these changes to the new file at `*/**/two-fer/mentoring.md`?

**Comment by PTrottier** [comment]
@SleeplessByte I am really having trouble with `git` at the moment, I'll have to look at this at a later time, hopefully by Sunday. Sorry for the inconvenience!

**Comment by SleeplessByte** [comment]
I don't know what happened here -- ha. 

My suggestion would be: reset the branch completely to master, and just copy over your changes, then force push :)

**Comment by PTrottier** [comment]
Thanks @SleeplessByte, your suggestion was most helpful :)

**Pull request merged**
