### PR TITLE
Updating use_substring comment for ``log-levels``

### PR DESCRIPTION
**Pull request by manumafe98**
The goal is to make the comment more clear for students

Related: [#151](https://github.com/exercism/java-analyzer/pull/151)

### CODE REVIEW

**Review by IsaacG — APPROVED** [review]

**Comment by sanderploegsma** [comment]
🤔 I'm not sure this should have been merged without the corresponding changes to the analyzer. Right now the copy contains a parameter but the analyzer doesn't provide the parameter in its output, so my guess is that the copy renders incorrectly for students...

**Comment by IsaacG** [comment]
Should we push a revert PR?

**Comment by sanderploegsma** [comment]
Yes I think that is best. And going forward we should try to avoid making breaking changes to existing comments.

Instead, we can consider creating a new version `comment_name_v2.md` next to the original one, so that we can safely update the analyzer asynchronously.

**Comment by sanderploegsma** [comment]
See https://github.com/exercism/website-copy/pull/2333

**Pull request merged**
