### PR TITLE
Improve java mentoring notes for TwoFer

### PR DESCRIPTION
**Pull request by chess4ever**

### CODE REVIEW

**Comment by chess4ever** [comment]
@sshine sorry but I don't understand your question

**Comment by chess4ever** [comment]
Oh yes sorry, I thought the "or" was a typo because as far as I have understood the solutions with String#format are much more readable than string concatanation.

**Comment by sshine** [comment]
Perhaps clarify that `String#format` is a good alternative wrt. clarity, since the original argument that comes after the "or" / "for" applied to `+` as well?

**Comment by chess4ever** [comment]
@sshine I agree, I have improved that suggestion.

**Comment by michael-berger-FR** [comment]
I don't see the button to display the Mentor Notes when I mentor TwoFer on the Java track. Am I missing something?

**Comment by SleeplessByte** [comment]
@michael-berger-FR best to cross-post your issue in https://github.com/exercism/exercism.
The button _should_ be in the top right of the sub-header.

**Comment by michael-berger-FR** [comment]
Thank you. I cross-posted it: [https://github.com/exercism/website/pull/443](https://github.com/exercism/website/pull/443)

**Pull request merged**
