### PR TITLE
Create 10.json

### PR DESCRIPTION
**Pull request by McZenith**

### CODE REVIEW

**Comment by rpottsoh** [comment]
@mczenith, you're on the right track.  You do not need to create a new file.  Your GitHub name starts with letter M, you should be updating file m.json for the language track you are mentoring.  I recommend that you read the [README](https://github.com/exercism/website-copy/blob/master/mentors/README.md#add-your-bio) that is present in the mentors folder.

**Comment by McZenith** [comment]
Thanks, everyone! I just figured it out...

**Comment by McZenith** [comment]
> Why create a new file 10.json? Shouldn't this go under `m.json` instead?

Thanks, I just figured.

**Comment by kotp** [comment]
If you remove the `10.json` file, this is probably good to merge, @McZenith

**Comment by rpottsoh** [comment]
And just some minor indentation issues.

**Pull request closed without merging**
