### PR TITLE
Add stevejb71 to OCaml mentoring

### PR DESCRIPTION
**Pull request by stevejb71**

### CODE REVIEW

**Comment by sshine** [comment]
@stevejb71: Perhaps, in case you have become inactive as a mentor, it is better to leave the impression that there are no active mentors on [this page](https://exercism.io/tracks/ocaml/mentors)? (I am no longer active as a mentor, but I continue as a passive maintainer.)

**Comment by rpottsoh** [comment]
If you are no longer able mentor exercises then it is probably best to remove yourself.  I understand your point about the track then appearing to have no mentors....
cc: @iHiD

**Comment by iHiD** [comment]
I guess if the track has no mentors it has no mentors. And it will be in oversubscribed mode.

**Comment by stevejb71** [comment]
I'm mentoring very infrequently now, so agree it's reasonable I should be removed.

**Comment by rpottsoh** [comment]
Open a PR that removes you from the json file.

**Pull request merged**
