### PR TITLE
Create mentoring guideline for reverse-string

### PR DESCRIPTION
**Pull request by EliseBriers**

### CODE REVIEW

**Review by siebenschlaefer — COMMENTED** [review]
I'm in favor of this PR.  
I'm just a little bit uncomfortable listing the O(n^2) approach as reasonable.

**Comment by siebenschlaefer** [comment]
Just two more small details:
- a trailing colon "in this case):"
- a typo "exeprions"

**Comment by siebenschlaefer** [comment]
Looks great!

**Review by siebenschlaefer — APPROVED** [review]
Sorry, I'm not used to being able to approve these things.

**Comment by EliseBriers** [comment]
> Sorry, I'm not used to being able to approve these things.  
> ... and apparently I don't have permissions. We'll have to wait for one of the big kids. :-)

Alright, np, looks like we're both still learning stuff :>

**Comment by siebenschlaefer** [comment]
To those with all the power: Is there anything missing? Should anything be improved? From my POV this is ready to be merged.

**Review by angelikatyborska — APPROVED** [review]
@siebenschlaefer I am not competent in C++ at all, so I can't review, but you're the #1 C++ mentor of all time on Exercism, so I'll trust you on this one and approve 🙂

**Pull request merged**
