### PR TITLE
go/twofer: mention exalysis mentoring tool

### PR DESCRIPTION
**Pull request by tehsphinx**
As discussed with @iHiD we want to mention github.com/tehsphinx/exalysis to help mentors start mentoring.

### CODE REVIEW

**Comment by iHiD** [comment]
Can you change this to be `###` pls?

**Comment by bitfield** [comment]
Change what to be what? 😀

**Comment by iHiD** [comment]
`##` to be `###`

**Comment by NobbZ** [comment]
@iHiD as you requested changes related to the formatting, would you mind approving?

**Pull request merged**
