### PR TITLE
Haskell: Leap mentoring notes

### PR DESCRIPTION
**Pull request by a59**
Adding new Mentoring notes for Haskell leap.

### CODE REVIEW

**Comment by sshine** [comment]
@a59, would you like to make these adjustments so I can merge your mentor notes?

**Comment by a59** [comment]
@sshine 

Sorry, I haven't quite worked out how to use GitHub properly yet. Please could you do this process right by starting again, and I'll close this request.

**Comment by sshine** [comment]
Ah, but I'm learning the GitHub workflow as well!

Just make another commit with the adjustments and I can squash merge them. :)

**Comment by sshine** [comment]
When you push to your feature branch, the PR gets updated automatically.

**Comment by a59** [comment]
I am closing this one and have opened another. I hope I am getting the workflow right this time.

I have tried to incorporate the comments of sshine.

**Pull request closed without merging**
