### PR TITLE
Add Dennis Hartrampf as mentor

### PR DESCRIPTION
**Pull request by DennisHartrampf**
Please add me as a mentor :)

### CODE REVIEW

**Comment by SleeplessByte** [comment]
Welcome to Java 👋

**Comment by rpottsoh** [comment]
Dennis, I noticed your bio contains an emoji.  I don't think the site will render it properly.  View your mentor bio on the site to see how "bio" appears.  You're welcome to open a PR to fix any changes you think might be necessary.

**Comment by SleeplessByte** [comment]
image

@rpottsoh unicode emojis (not in the extended set) definitely work fine :)

**Comment by rpottsoh** [comment]
Awesome, good to know.  Thanks for confirming.

**Pull request merged**
