### PR TITLE
Add mentoring notes for elixir/bank-account

### LINKED ISSUE #1340: elixir/bank-account: mentoring notes

### PR DESCRIPTION
**Pull request by filalex77**
Closes #1340.

### CODE REVIEW

**Comment by filalex77** [comment]
@neenjaw I came up with this; can you mentor me? 😺 

```elixir
defmodule BankAccount do
  @opaque account :: pid

  defp listen(from, balance) do
    new_balance =
      receive do
        :balance ->
          send(from, balance)
          balance

        {:update, amount} ->
          balance + amount
      end

    listen(from, new_balance)
  end

  @spec open_bank() :: account
  def open_bank(), do: spawn(fn -> listen(self(), 0) end)

  @spec close_bank(account) :: true
  def close_bank(account), do: Process.exit(account, :kill)

  @spec balance(account) :: integer
  def balance(account) do
    if Process.alive?(account) do
      send(account, :balance)

      receive do
        balance -> balance
      end
    else
      {:error, :account_closed}
    end
  end

  @spec update(account, integer) :: any
  def update(account, amount) do
    if Process.alive?(account) do
      send(account, {:update, amount})
    else
      {:error, :account_closed}
    end
  end
end
```

**Comment by neenjaw** [comment]
I think your example using spawn, send, receive is quite nice and people can see how these work with a quick read through.

This exercise is tricky sometimes because people often make it complicated when the goal of this exercise is to show how messaging and concurrency works in elixir.

I think you should incorporate this. 

I'd like @chriseyre2000 to take a peek at this since when I did this exercise, he suggested I look for the variants incase there are features he thinks would be good to include.

**Comment by chriseyre2000** [comment]
My previous entry was rejected as being too long.

There is a fourth solution that I have seen:

https://exercism.io/tracks/elixir/exercises/bank-account/solutions/1aee1d83a73944109bde989399a6861d

**Comment by neenjaw** [comment]
@SleeplessByte - out of curiosity, how does this PR get merged? It would be nice to have for mentors

**Comment by SleeplessByte** [comment]
@neenjaw I would expect someone with decent elixer knowledge to approve this, but it seems like that's you so here we go!

**Pull request merged**
