### PR TITLE
Add mentor notes for JavaScript leap exercise

### PR DESCRIPTION
**Pull request by alexZielonko**

### CODE REVIEW

**Comment by SleeplessByte** [comment]
@ErikSchierboom want me to add to this? F

or example, the reasonable solutions in this one lack parentheses and therefore are logically wrong (execute the is divisible by 400 branch each invocation it's not divisible by 4).

**Comment by ErikSchierboom** [comment]
> @ErikSchierboom want me to add to this?

It's not up to me to decide. What I would like is that the two PR authors decide upon a single PR to use. Whichever that is, or with which changes, does not matter to me. Just that there is one PR :)

**Comment by iHiD** [comment]
I'm merging this and then @SleeplessByte could you PR any of your improvements to master pls? Thanks both.

**Comment by SleeplessByte** [comment]
Yep! will do 👍

**Pull request merged**
