### PR TITLE
Create mentoring.md

### PR DESCRIPTION
**Pull request by RomaLetodiani**
Flatten Array
JavaScript

### CODE REVIEW

**Comment by IsaacG** [comment]
Typically the mentoring notes include notes and details, not sample solutions. Mentors can always look at the community solutions to see sample solutions.

**Comment by RomaLetodiani** [comment]
I'll consider it for next time, thanks for the response, i am new to this.

**Comment by IsaacG** [comment]
You can always look at other mentoring notes to get a sense for what they ought to look at. It would be good to understand what notes typically look at prior to creating a new notes file.

**Comment by RomaLetodiani** [comment]
There was no note on this particular task

**Comment by IsaacG** [comment]
There are notes on other exercises you can read to get an idea of what notes ought to look like. Please try to do some reading and homework before opening a PR.

**Pull request closed without merging**
