### PR TITLE
Change comment format

### PR DESCRIPTION
**Pull request by neenjaw**
Change to `[comment]: # (this is a comment)`

### CODE REVIEW

**Comment by neenjaw** [comment]
@iHiD

**Comment by angelikatyborska** [comment]
https://stackoverflow.com/a/32190021/5726486 this says that there needs to be an empty line before that fake link. But I don't really understand why.

**Comment by neenjaw** [comment]
I'm just going with what @iHiD had suggested we try.  He had an example here: https://johnmacfarlane.net/babelmark2/?text=above%0A%0A%5Bcomment%5D%3A+%23+(THIS+SHOULD+BE+REMOVED)%0Abelow

**Comment by neenjaw** [comment]
And if you view the file with rich display, it is hidden from view in GitHub. So I'm hopeful it will work on the website

**Comment by iHiD** [comment]
> says that there needs to be an empty line before that fake link.

If I understand correctly (which is far from certain) it's because if there's not it'll get treated as part of the same paragraph as the line above, rather than it's own thing. But this doesn't matter if it's the first line.

**Review by iHiD — APPROVED** [review]

**Comment by neenjaw** [comment]
I don't have write access to merge this, thanks for approving though!

**Comment by iHiD** [comment]
@neenjaw Weeeeeird!. You do now :)

**Pull request merged**
