### PR TITLE
elixir: Update variable_name_snake_case.md

### PR DESCRIPTION
**Pull request by cmcaine**
I'm not totally sure that the wrong_name will be camelCase, but it seems likely?

analyser bit: https://github.com/exercism/elixir-analyzer/blob/main/lib/elixir_analyzer/exercise_test/common_checks/variable_names.ex

### CODE REVIEW

**Comment by angelikatyborska** [comment]
Oh. I think the comment is not explicit enough and we have interpreted it in two opposite ways.

My intention was:

```elixir
# this is snake_case
do_something

# this is not snake_cake
# doSomething
```

But another interpretation, which I guess you had because of the change you're suggesting, is:
```elixir
# use snake_case
do_something

# do not use camelCase
# doSomething
```

We should make this more explicit. Can you make an additional change? I don't really care which version we use.

**Comment by cmcaine** [comment]
That makes sense, updated :)

**Review by angelikatyborska — DISMISSED** [review]

**Comment by angelikatyborska** [comment]
Wait, I forgot about the other files! If we're changing the comment in one of them because it's confusing, we should update all. They all have this kind of comment:
- analyzer-comments/elixir/solution/function_name_snake_case.md
- analyzer-comments/elixir/solution/module_attribute_name_snake_case.md
- analyzer-comments/elixir/solution/module_pascal_case.md

**Review by angelikatyborska — APPROVED** [review]
Perfect, thanks!

**Pull request merged**
