### PR TITLE
Add mentoring/python/triangles

### PR DESCRIPTION
**Pull request by IsaacG**

### CODE REVIEW

**Comment by IsaacG** [comment]
@BethanyG or @kotp  for approval

**Comment by BethanyG** [comment]
Apologies.  Using GH Desktop client for first time, and it picked up some garbage.  Fixing shortly.

**Comment by IsaacG** [comment]
> Apologies. Using GH Desktop client for first time, and it picked up some garbage. Fixing shortly.

I think I got them all.

**Comment by BethanyG** [comment]
I forget where this appears on the tree, but a side note about generator expressions might be good here -- just because they are referred to multiple times in the text and a student may or may not "know" them at this point.  But that's a minor suggestion.  Otherwise, this looks good.  Approving.

**Review by BethanyG — DISMISSED** [review]

**Comment by IsaacG** [comment]
Added a note about generators. If that looks good to you, feel free to merge. I cannot merge PRs.

**Review by BethanyG — APPROVED** [review]
Looks good.  Merging.

**Pull request merged**
