### PR TITLE
 walkthrough: Improve grammar on index.html

### PR DESCRIPTION
**Pull request by kkelleey**
See [this Reply All episode](https://gimletmedia.com/shows/reply-all/94hw2v/14-the-art-of-making-and-fixing-mistakes) (TL;DR it's often misused but should either be "composed of" or "comprises")

### CODE REVIEW

**Review by Stargator — APPROVED** [review]

**Comment by Stargator** [comment]
@iHiD I think this is good to merge, it's been awhile since I was active in this repo. Am I missing anything in terms of process or whether the `master` branch is the correct branch?

**Comment by SleeplessByte** [comment]
@Stargator site-wide copy we usually have reviewed by someone from @exercism/product . Apart from that, all is good.

**Comment by iHiD** [comment]
Sorry for the slow reply and thanks for this. This needs fixing upstream in https://github.com/exercism/interactive-cli-walkthrough - this file is auto-generated from that repo. @kkelleey Could you add the fix there pls and tag @kntsoriano in it and we'll get it merged this week 🙂

**Comment by DanielNoord** [comment]
https://github.com/exercism/interactive-cli-walkthrough/pull/114 has been merged so this can be closed.

Not sure who to ping here, but @iHiD I think you have the rights to close this?

**Comment by iHiD** [comment]
Thanks all!

**Pull request closed without merging**
