### PR TITLE
[Ruby] High Scores: mentor notes update

### PR DESCRIPTION
**Pull request by kotp**
Using take forces sort in the solution, using max instead does work for us.
    
Update note to support the change.

### CODE REVIEW

**Review by DioXi95 — COMMENTED** [review]
tracks/$track_id/exercises/$exercise_slug/mentoring.md

**Comment by kotp** [comment]
> tracks/$track_id/exercises/$exercise_slug/mentoring.md

Can you explain what to do with this?

**Comment by SleeplessByte** [comment]
Uhhhh. Where is that @kotp ?

Can you add newlines below the headings?

**Comment by kotp** [comment]
> Uhhhh. Where is that @kotp ?

This was coming from the CI at one point, I believe.
 
> Can you add newlines below the headings?

Done

**Pull request closed without merging**
