### PR TITLE
add initial mentor notes for Crystal/Raindrops

### PR DESCRIPTION
**Pull request by tenebrousedge**
Please let me know if there are typographic or code errors, or if the advice is less than sensible.

### CODE REVIEW

**Comment by sshine** [comment]
@tenebrousedge: I see that you have a bunch of mentor notes waiting for review. They seem very well-written, and while I have no experience with Crystal, I'd be happy to go over them all and approve and merge them once I get back from vacation. It seems a pity that mentors do not currently have access to them.

**Comment by tenebrousedge** [comment]
Are there any further objections to merging these PRs?

**Comment by SleeplessByte** [comment]
https://github.com/exercism/website-copy/pull/975#pullrequestreview-233794904 was never resolved.

**Comment by tenebrousedge** [comment]
It was resolved. The section names are not set in stone, and there are no objective reasons for preferring one way or another.

**Pull request merged**
