### PR TITLE
Remove personal development environment ignores

### PR DESCRIPTION
**Pull request by kotp**
The `.gitignore` for the project should have things that this project should ignore, yet may create.

The "global" gitignore is for things for developers environment.

### CODE REVIEW

**Comment by angelikatyborska** [comment]
I agree 100% but I recall @SleeplessByte recently voiced the opposite opinion. If he doesn't have anything against this PR here, I would approve.

**Comment by SleeplessByte** [comment]
In general I could agree with this, but we really never want that folder submitted right? So why should it not be in the project gitignore?

**Comment by angelikatyborska** [comment]
Right, but having a gitignore with a single environment-specific file opens up the door for everyone to open PRs that add more environment-specific patterns, for their Jetbrains files, VSC files, vim swap files etc. etc., adding a bit more work for us to review all of that. In the end, it's basically just about giving a good example.

**Review by angelikatyborska — APPROVED** [review]

**Comment by kotp** [comment]
Thanks for the review, and yes @angelikatyborska has it exactly right.

**Pull request merged**
