### PR TITLE
julia/difference-of-squares: Use ÷ and Gauss's formula

### PR DESCRIPTION
**Pull request by SaschaMann**

### CODE REVIEW

**Comment by SaschaMann** [comment]
Do images work in the mentor notes?

**Comment by SleeplessByte** [comment]
Hi @SaschaMann. Is there a reason the solution is missing? (just like in [custom-set](https://github.com/exercism/website-copy/blob/master/tracks/julia/exercises/custom-set/mentoring.md)).

**Comment by SaschaMann** [comment]
Yes, I don't have a decent example solution for it, but wanted to add the hint anyway.

---
The review request won't work because I'm the only one in that team and I can't approve my own PR.

**Comment by SleeplessByte** [comment]
Can you remove the empty block (`Reasonable Solution`) and preferably add a blank line after each header (see markdown lint).

I'll merge it afterwards.

**Comment by SaschaMann** [comment]
Done, thank you.

**Pull request merged**
