### PR TITLE
Ruby: Raindrops - reasonable with each_with_object

### PR DESCRIPTION
**Pull request by kotp**
Ref: #883

### CODE REVIEW

**Comment by SleeplessByte** [comment]
I personally like it; perhaps it could helpt to add a line _why_ this is nice? -- there is a conflict.

**Comment by kotp** [comment]
> there is a conflict.

Introduced due to the other being merged into master, taken care of.

As far as a comment as to why is this nice?  Can a mentor identify that via the code?  There are several aspects in the code that aren't relevant to the problem itself, such as the vertical layout of the rules, the mutable allow indicator of the string literal which is only valid on some versions of Ruby, etc.

**Comment by SleeplessByte** [comment]
Gotcha! Good question.

Basically I am saying, perhaps you want to
- add at line 2 or line 15 that the first solution uses a mutable string
- add at line 15 or line 32 that the second solution uses `each_with_object` over the rules object, then add them if they pass a test
- add at line 32 or line 43 that the third solution selects the correct rules by testing them and then joining the selected rules

I know it's apparent from the code, but writing it out might help a mentor as the cognitive complexion is way lower that way. As you said yourself: many things aren't relevant and adding a line of clarification _what is relevant_ goes a long way.

**Comment by SleeplessByte** [comment]
Thanks @kotp ! Great addition.

**Pull request merged**
