### PR TITLE
python/general: Add notes on Variables and Simplicity

### PR DESCRIPTION
**Pull request by jeffdparker**

### CODE REVIEW

**Comment by SleeplessByte** [comment]
@jeffdparker there seems to be a conflict!

**Comment by SleeplessByte** [comment]
@jeffdparker there seems to be a conflict.

**Comment by jeffdparker** [comment]
Oh, dear.  Is the problem the 4th \` on lines 205 & 209?

````python

````

**Comment by SleeplessByte** [comment]
I think I fixed it @jeffdparker 👍

**Pull request merged**
