### PR TITLE
Added elixir robot-simulator mentoring notes

### PR DESCRIPTION
**Pull request by chriseyre2000**
Added robot-simulator mentoring notes.

### CODE REVIEW

**Comment by SleeplessByte** [comment]
What was wrong with https://github.com/exercism/website-copy/pull/810 ? You may always squash and force push, but we can also squash on merge.

**Comment by SleeplessByte** [comment]
For @exercism/website-copy-elixir I don't know if this is present in all your notes. In Ruby, JS and TS we explicitely remove Rdoc/Yard/JSDoc/TSDoc from reasonable solutions as we don't want to encourage mentors to enforce students writing docs.

**Comment by chriseyre2000** [comment]
> What was wrong with #810 ? You may always squash and force push, but we can also squash on merge.

I had accidentally included other changes in one commit. I had been asked to split it.

**Comment by chriseyre2000** [comment]
> For @exercism/website-copy-elixir I don't know if this is present in all your notes. In Ruby, JS and TS we explicitely remove Rdoc/Yard/JSDoc/TSDoc from reasonable solutions as we don't want to encourage mentors to enforce students writing docs.

I would need to add @moduledoc false as not having docs is a warning. Documentation is a first class citizen in Elixir.

**Comment by NobbZ** [comment]
As I am not allowed to comment inline:

> I would need to add @moduledoc false as not having docs is a warning.

My compiler does not generate a warning for missing documentation…

**Comment by NobbZ** [comment]
PS: I have not done the exercise in elixir yet, therefor I won't review this information. But on a first glance it seems to be far to much code to read, which will probably differ massively from each students submission, while having far to much free-form text about things to look at.

As a mentor I'd probably run away from such a mentor note, as it looks like any other **students** submission.

**Comment by chriseyre2000** [comment]
This has two distinct solutions.

**Comment by chriseyre2000** [comment]
I have split the two solutions and removed the docs.

**Comment by SleeplessByte** [comment]
Looks cleaner. Can you move the ` # GenServer` and `# Recursive` out of the solution, and make it a heading with some guidance?

```diff
  ### Reasonable solutions
+ 
+ There are various valid solutions, including using a gen server or using a recursive approach:
+ 
+ #### Using  GenServer 
+ 
  ```elixir
- # GenServer
  
   defmodule Robot do
```

**Comment by SleeplessByte** [comment]
Thank you @chriseyre2000 ❤️ . Pinging @exercism/website-copy-r.

**Comment by SleeplessByte** [comment]
Thank you @chriseyre2000 ❤️ . Pinging @exercism/website-copy-elixir.

**Comment by rpottsoh** [comment]
Pinging @exercism/website-copy-elixir.  Should other people be pinged as well?

**Comment by neenjaw** [comment]
As requested by @SleeplessByte in the #track-elixir channel on slack, I looked over the mentoring notes, they look reasonable and follows closely with how I mentor solutions.  I cannot comment on the formatting or how they might display on the exercism site.

**Comment by SleeplessByte** [comment]
Thank you @neenjaw :heart: and @chriseyre2000!

**Pull request merged**
