### PR TITLE
Labeller: Add labelling rules

### LINKED ISSUE #1250: issue template: provide one that suggests "tagging" the title
Please provide an issue/PR template that asks to tag the title accordingly.

This repository has a lot of subtopics. And those even split further into tracks, such that there are a lot of responsibilities divided through out the repository.

Often titles of PRs and issues are poorly choosen and its hard to know wether or not its related to an individual or team.

Therefore I suggest an issue template that asks the creator to provide a proper title and description.

* Issues and PRs that are for mentornotes should be "tagged" by track and exercise, eg: `mentornotes/javascript/hello-world: add notes", `mentornotes/erlang/two-fer: fix typo`
* Issues and PRs that are for mentor bios should be tagged by track at least, eg: `bio/javascript: add myself`, `bio/ruby: fix avatar of foomtor`, `bio/python: add ham and eggs to description of PyBaker`
* Issues and PRs that are for analyzer comments should also contain track and exercise, eg: `analyzer/elixir/two-fer: create comments`

Perhaps there are further sub projects which need additional tagging.

Exact tags to use and which sub projects need their own is subject to discussion, above are just examples.

As part of this, I'd also suggest to add more codeowners as necessary for the analyzer, mentor bios, etc, as soon as we know more details about #1249.

### PR DESCRIPTION
**Pull request by NobbZ**
This PR finally closes #1250 by automatically labeling according to languages.

### CODE REVIEW

**Comment by SleeplessByte** [comment]
Given #1284, do you want to merge this already or wait?

**Comment by SleeplessByte** [comment]
FWIW: `track/swift` is missing. Is it possible that more are missing?

**Comment by iHiD** [comment]
Any reason this isn't merged?

**Comment by SleeplessByte** [comment]
It doesn't work yet on outside collaborator PRs or something like that?

**Comment by iHiD** [comment]
Ah - the title of the issue confused me. I thought this was the PR to actually add the labels, not add them to the labeller. I will update it.

**Comment by angelikatyborska** [comment]
The labeler was configured and added in another PR (https://github.com/exercism/website-copy/pull/1858) because:

- this one didn't have any activity since 2019
- this one didn't add the necessary github workflow for the labeler

**Pull request closed without merging**
